/**
 * Copyright (c) 2026 Micelclaw (Víctor García Valdunciel)
 * All rights reserved.
 *
 * This file is part of Micelclaw OS and is proprietary software.
 * Unauthorized copying, modification, distribution, or use of this
 * file, via any medium, is strictly prohibited.
 *
 * See LICENSE in the root of this repository for full terms.
 * https://micelclaw.com
 */

import { useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router';
import { toast } from 'sonner';
import { useWebSocket } from '@/hooks/use-websocket';
import { useDiagramsStore } from '@/stores/diagrams.store';
import type { DiagramFile } from '../types';

/**
 * Listens for AI-driven diagram WebSocket events and loads them into the store.
 * - `diagrams:load`   → new diagram generated by AI
 * - `diagrams:update` → existing diagram modified by AI
 */
export function useDiagramWs() {
  const navigate = useNavigate();
  const location = useLocation();
  const loadEvent = useWebSocket('diagrams:load');
  const updateEvent = useWebSocket('diagrams:update');

  // Handle new diagram from AI
  useEffect(() => {
    if (!loadEvent) return;
    const diagram = loadEvent.data.diagram as DiagramFile;
    if (!diagram) return;

    // If on launcher (not in editor), navigate to editor first
    if (location.pathname === '/diagrams' || location.pathname === '/diagrams/') {
      navigate('/diagrams/new');
    }

    useDiagramsStore.getState().loadDiagram(diagram);
    toast.success('Diagram generated');
  }, [loadEvent, navigate, location.pathname]);

  // Handle diagram update from AI
  useEffect(() => {
    if (!updateEvent) return;
    const diagram = updateEvent.data.diagram as DiagramFile;
    const fileId = updateEvent.data.file_id as string | undefined;
    if (!diagram) return;

    useDiagramsStore.getState().loadDiagram(diagram, fileId);
    const changes = updateEvent.data.changes as string | undefined;
    toast.success(changes ? `Diagram updated: ${changes}` : 'Diagram updated');
  }, [updateEvent]);
}
