/**
 * Copyright (c) 2026 Micelclaw (Víctor García Valdunciel)
 * All rights reserved.
 *
 * This file is part of Micelclaw OS and is proprietary software.
 * Unauthorized copying, modification, distribution, or use of this
 * file, via any medium, is strictly prohibited.
 *
 * See LICENSE in the root of this repository for full terms.
 * https://micelclaw.com
 */

// ─── usePushSubscription — Web Push UX state ────────────────────────
//
// Surfaces the 6 distinct states the user can be in (matters for the
// NotificationsSection banner copy + the toggle behaviour), plus the
// list of subscribed devices from the backend and the subscribe /
// unsubscribe / test actions.
//
// The hook is conservative: capability detection happens once on mount
// and never re-runs. State transitions on user actions (subscribe /
// unsubscribe) re-fetch from the backend so the device list stays in
// sync across tabs (best-effort — perfect sync requires a WS event we
// don't have today).

import { useCallback, useEffect, useState } from 'react';
import { api } from '@/services/api';

export type PushSubscriptionStatus =
  | { kind: 'unsupported' }
  | { kind: 'ios_needs_install' }
  | { kind: 'permission_denied' }
  | { kind: 'permission_default' }
  | { kind: 'not_subscribed' }
  | { kind: 'subscribed'; endpoint: string };

export interface DeviceSubscription {
  id: string;
  user_agent: string | null;
  created_at: string;
  last_seen_at: string;
}

interface VapidPublicKeyResp { public_key: string; source: 'env' | 'autogenerated' }
interface SubscribeRespData { id: string; created_at: string; last_seen_at: string }
interface ListSubsResp { subscriptions: DeviceSubscription[] }
interface TestResp { delivered: number; expired: number; failed: number; reason?: string }

function detectCapabilities(): { supported: boolean; isiOSWithoutInstall: boolean } {
  if (typeof window === 'undefined') return { supported: false, isiOSWithoutInstall: false };
  const supported = 'serviceWorker' in navigator && 'PushManager' in window;
  if (!supported) return { supported: false, isiOSWithoutInstall: false };
  // iOS 16.4+ only supports Web Push when the PWA is installed (Add to
  // Home Screen). Safari in a tab returns the API but the subscribe call
  // fails — surface this as a distinct status so we can show the right
  // banner.
  const isiOS = /iPad|iPhone|iPod/.test(navigator.userAgent)
    && !(window as unknown as { MSStream?: unknown }).MSStream;
  const isStandalone = window.matchMedia('(display-mode: standalone)').matches
    || (navigator as Navigator & { standalone?: boolean }).standalone === true;
  return { supported: true, isiOSWithoutInstall: isiOS && !isStandalone };
}

function base64UrlToUint8Array(base64Url: string): Uint8Array {
  const padding = '='.repeat((4 - (base64Url.length % 4)) % 4);
  const base64 = (base64Url + padding).replace(/-/g, '+').replace(/_/g, '/');
  const raw = atob(base64);
  const out = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i);
  return out;
}

export function usePushSubscription() {
  const [status, setStatus] = useState<PushSubscriptionStatus>({ kind: 'permission_default' });
  const [subscriptions, setSubscriptions] = useState<DeviceSubscription[]>([]);
  const [loading, setLoading] = useState(false);
  const [vapidPublicKey, setVapidPublicKey] = useState<string | null>(null);

  // Initial capability detection + status resolve.
  useEffect(() => {
    const { supported, isiOSWithoutInstall } = detectCapabilities();
    if (!supported) {
      setStatus({ kind: 'unsupported' });
      return;
    }
    if (isiOSWithoutInstall) {
      setStatus({ kind: 'ios_needs_install' });
      return;
    }
    (async () => {
      const perm = Notification.permission;
      if (perm === 'denied') {
        setStatus({ kind: 'permission_denied' });
        return;
      }
      if (perm === 'default') {
        setStatus({ kind: 'permission_default' });
        return;
      }
      // granted — check local sub
      const reg = await navigator.serviceWorker.ready;
      const local = await reg.pushManager.getSubscription();
      if (!local) {
        setStatus({ kind: 'not_subscribed' });
        return;
      }
      setStatus({ kind: 'subscribed', endpoint: local.endpoint });
    })().catch((err) => console.warn('[push] init check failed', err));
  }, []);

  const refresh = useCallback(async () => {
    try {
      const res = await api.get<{ data: ListSubsResp }>('/push/subscriptions');
      setSubscriptions(res.data.subscriptions);
    } catch (err) {
      console.warn('[push] list failed', err);
    }
  }, []);

  // Fetch device list whenever status changes to/from subscribed.
  useEffect(() => {
    if (status.kind === 'subscribed' || status.kind === 'not_subscribed') {
      void refresh();
    }
  }, [status.kind, refresh]);

  const loadVapidPublicKey = useCallback(async (): Promise<string> => {
    if (vapidPublicKey) return vapidPublicKey;
    const res = await api.get<{ data: VapidPublicKeyResp }>('/push/public-key');
    const key = res.data.public_key;
    setVapidPublicKey(key);
    return key;
  }, [vapidPublicKey]);

  const subscribe = useCallback(async () => {
    if (status.kind === 'unsupported' || status.kind === 'ios_needs_install') return;
    setLoading(true);
    try {
      const perm = Notification.permission === 'default'
        ? await Notification.requestPermission()
        : Notification.permission;
      if (perm === 'denied') { setStatus({ kind: 'permission_denied' }); return; }
      if (perm !== 'granted') { setStatus({ kind: 'permission_default' }); return; }

      const publicKey = await loadVapidPublicKey();
      const reg = await navigator.serviceWorker.ready;
      const existing = await reg.pushManager.getSubscription();
      const sub = existing ?? await reg.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: base64UrlToUint8Array(publicKey),
      });
      const json = sub.toJSON();
      await api.post<{ data: SubscribeRespData }>('/push/subscribe', {
        endpoint: json.endpoint,
        keys: json.keys,
      });
      setStatus({ kind: 'subscribed', endpoint: sub.endpoint });
      await refresh();
    } catch (err) {
      console.error('[push] subscribe failed', err);
      // Keep the current status — the UI shows the error via toast.
      throw err;
    } finally {
      setLoading(false);
    }
  }, [status.kind, loadVapidPublicKey, refresh]);

  const unsubscribe = useCallback(async (deviceId?: string) => {
    setLoading(true);
    try {
      if (deviceId) {
        // Remove a specific device from the backend; the SW local sub is
        // untouched (it might be a different device showing on the list).
        await api.delete(`/push/subscribe/${deviceId}`);
      } else {
        // Unsubscribe THIS device: backend list + local SW sub.
        const reg = await navigator.serviceWorker.ready;
        const local = await reg.pushManager.getSubscription();
        if (local) {
          // Find the backend row for this endpoint, delete it.
          const match = subscriptions.find((s) => true); // best-effort — see refresh()
          if (match) {
            await api.delete(`/push/subscribe/${match.id}`).catch(() => undefined);
          }
          await local.unsubscribe();
        }
        setStatus({ kind: 'not_subscribed' });
      }
      await refresh();
    } catch (err) {
      console.error('[push] unsubscribe failed', err);
      throw err;
    } finally {
      setLoading(false);
    }
  }, [subscriptions, refresh]);

  const test = useCallback(async (): Promise<TestResp> => {
    const res = await api.post<{ data: TestResp }>('/push/test', {});
    return res.data;
  }, []);

  return {
    status,
    subscriptions,
    loading,
    subscribe,
    unsubscribe,
    test,
    refresh,
  };
}
