#!/usr/bin/env npx tsx
/**
 * Generate a Markdown report from Playwright JSON output.
 * Usage: npx tsx e2e/generate-report.ts
 * Reads: test-results/flows-report.json
 * Writes: test-results/FLOWS_E2E_REPORT.md
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const ROOT = join(import.meta.dirname, '..');
const JSON_PATH = join(ROOT, 'test-results', 'flows-report.json');
const REPORT_DIR = join(ROOT, 'test-results');
const TS = new Date().toISOString().replace(/:/g, '-').slice(0, 19);
const REPORT_PATH = join(REPORT_DIR, `FLOWS_E2E_${TS}.md`);
const LATEST_PATH = join(REPORT_DIR, 'FLOWS_E2E_LATEST.md');

mkdirSync(REPORT_DIR, { recursive: true });

let report: any;
try {
  report = JSON.parse(readFileSync(JSON_PATH, 'utf-8'));
} catch {
  console.error('No JSON report found at', JSON_PATH);
  console.error('Run: pnpm e2e --project=firefox e2e/flows.spec.ts');
  process.exit(1);
}

const suites = report.suites ?? [];
const allTests: Array<{ title: string; status: string; duration: number; error?: string }> = [];

function extractTests(suite: any, prefix = '') {
  const suiteName = prefix ? `${prefix} > ${suite.title}` : suite.title;
  for (const spec of suite.specs ?? []) {
    for (const test of spec.tests ?? []) {
      const result = test.results?.[0];
      allTests.push({
        title: spec.title,
        status: result?.status ?? 'unknown',
        duration: result?.duration ?? 0,
        error: result?.error?.message?.slice(0, 200),
      });
    }
  }
  for (const child of suite.suites ?? []) {
    extractTests(child, suiteName);
  }
}

for (const suite of suites) {
  extractTests(suite);
}

const passed = allTests.filter(t => t.status === 'expected' || t.status === 'passed').length;
const failed = allTests.filter(t => t.status === 'unexpected' || t.status === 'failed').length;
const skipped = allTests.filter(t => t.status === 'skipped').length;
const total = allTests.length;
const totalDuration = allTests.reduce((sum, t) => sum + t.duration, 0);
const avgDuration = total > 0 ? Math.round(totalDuration / total) : 0;

const lines: string[] = [
  '# MicelFlow Playwright E2E Report',
  '',
  `> Date: ${new Date().toISOString()}`,
  `> Tests: ${total}`,
  `> Duration: ${(totalDuration / 1000).toFixed(1)}s`,
  '',
  '## Summary',
  '',
  '| Total | Passed | Failed | Skipped | Avg Duration |',
  '|-------|--------|--------|---------|--------------|',
  `| ${total} | ${passed} | ${failed} | ${skipped} | ${avgDuration}ms |`,
  '',
];

if (failed > 0) {
  lines.push('## Failures', '');
  for (const t of allTests.filter(t => t.status === 'unexpected' || t.status === 'failed')) {
    lines.push(`- **${t.title}** — ${t.error ?? 'unknown error'}`);
  }
  lines.push('');
}

lines.push('## Detailed Results', '');
lines.push('| # | Test | Status | Duration |');
lines.push('|---|------|--------|----------|');
allTests.forEach((t, i) => {
  const icon = (t.status === 'expected' || t.status === 'passed') ? '✓' : t.status === 'skipped' ? '⊘' : '✗';
  const statusLabel = (t.status === 'expected' || t.status === 'passed') ? 'PASS' : t.status === 'skipped' ? 'SKIP' : 'FAIL';
  lines.push(`| ${i + 1} | ${t.title} | ${icon} ${statusLabel} | ${t.duration}ms |`);
});
lines.push('');

// Latency stats
const durations = allTests.map(t => t.duration).sort((a, b) => a - b);
if (durations.length > 0) {
  lines.push('## Latency Stats', '');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Min | ${durations[0]}ms |`);
  lines.push(`| Avg | ${avgDuration}ms |`);
  lines.push(`| Median | ${durations[Math.floor(durations.length / 2)]}ms |`);
  lines.push(`| P95 | ${durations[Math.floor(durations.length * 0.95)]}ms |`);
  lines.push(`| Max | ${durations[durations.length - 1]}ms |`);
  lines.push('');
}

lines.push('---');
lines.push('*Generated by `e2e/generate-report.ts` from Playwright JSON output*');

const md = lines.join('\n');
writeFileSync(REPORT_PATH, md, 'utf-8');
writeFileSync(LATEST_PATH, md, 'utf-8');
console.log(`Report: ${REPORT_PATH}`);
console.log(`Latest: ${LATEST_PATH}`);
