import { useState, useEffect, useCallback } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { api } from '@/services/api';

interface DigestEntry {
  id: string;
  changes_count: number;
  domains: string[];
  raw_summary: string;
  alert_level: string | null;
  intelligent_summary: string | null;
  action_suggested: string | null;
  channels_delivered: string[];
  delivered_at: string;
}

const PAGE_SIZE = 20;

const LEVEL_COLORS: Record<string, string> = {
  SILENT: 'var(--text-muted)',
  NORMAL: 'var(--amber)',
  URGENT: 'var(--error)',
};

export function Component() {
  const [entries, setEntries] = useState<DigestEntry[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(0);
  const [loading, setLoading] = useState(true);

  const fetchHistory = useCallback(async () => {
    setLoading(true);
    try {
      const res = await api.get<{ data: DigestEntry[]; meta: { total: number } }>('/digest/history', {
        limit: PAGE_SIZE,
        offset: page * PAGE_SIZE,
      });
      setEntries(res.data);
      setTotal(res.meta?.total ?? res.data.length);
    } catch {
      setEntries([]);
    }
    setLoading(false);
  }, [page]);

  useEffect(() => { fetchHistory(); }, [fetchHistory]);

  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));

  return (
    <div style={{
      maxWidth: 720,
      margin: '0 auto',
      padding: '24px 16px',
      fontFamily: 'var(--font-sans)',
    }}>
      <h1 style={{
        fontSize: '1.25rem',
        fontWeight: 700,
        color: 'var(--text)',
        margin: '0 0 4px',
      }}>
        Digest History
      </h1>
      <p style={{ fontSize: '0.8125rem', color: 'var(--text-muted)', margin: '0 0 24px' }}>
        All digest summaries generated by the system.
      </p>

      {loading ? (
        <div style={{ padding: 32, textAlign: 'center', color: 'var(--text-muted)', fontSize: '0.875rem' }}>
          Loading...
        </div>
      ) : entries.length === 0 ? (
        <div style={{ padding: 32, textAlign: 'center', color: 'var(--text-muted)', fontSize: '0.875rem' }}>
          No digest entries yet.
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {entries.map(entry => (
            <div
              key={entry.id}
              style={{
                background: 'var(--surface)',
                border: '1px solid var(--border)',
                borderRadius: 'var(--radius-md)',
                padding: '12px 16px',
              }}
            >
              {/* Header: time + level + count */}
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
                <span style={{
                  fontSize: '0.6875rem',
                  fontFamily: 'var(--font-mono)',
                  color: 'var(--text-muted)',
                }}>
                  {new Date(entry.delivered_at).toLocaleString()}
                </span>
                {entry.alert_level && (
                  <span style={{
                    fontSize: '0.625rem',
                    fontWeight: 700,
                    padding: '1px 6px',
                    borderRadius: 'var(--radius-sm)',
                    background: `color-mix(in srgb, ${LEVEL_COLORS[entry.alert_level] ?? 'var(--text-muted)'} 15%, transparent)`,
                    color: LEVEL_COLORS[entry.alert_level] ?? 'var(--text-muted)',
                  }}>
                    {entry.alert_level}
                  </span>
                )}
                <span style={{ fontSize: '0.6875rem', color: 'var(--text-dim)' }}>
                  {entry.changes_count} changes
                </span>
              </div>

              {/* AI Summary */}
              {entry.intelligent_summary && (
                <p style={{ fontSize: '0.8125rem', color: 'var(--text)', margin: '0 0 6px', lineHeight: 1.5 }}>
                  {entry.intelligent_summary}
                </p>
              )}

              {/* Action suggested */}
              {entry.action_suggested && entry.action_suggested !== 'null' && (
                <p style={{ fontSize: '0.75rem', color: 'var(--text-dim)', margin: '0 0 8px', fontStyle: 'italic' }}>
                  {entry.action_suggested}
                </p>
              )}

              {/* Domain chips */}
              <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
                {entry.domains.map(d => (
                  <span key={d} style={{
                    fontSize: '0.625rem',
                    padding: '1px 6px',
                    borderRadius: 'var(--radius-sm)',
                    background: 'var(--surface-hover)',
                    color: 'var(--text-dim)',
                    textTransform: 'capitalize',
                  }}>
                    {d}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Pagination */}
      {total > PAGE_SIZE && (
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: 12,
          marginTop: 16,
        }}>
          <button
            onClick={() => setPage(p => p - 1)}
            disabled={page === 0}
            style={{
              display: 'flex', alignItems: 'center', gap: 4,
              padding: '4px 10px', border: '1px solid var(--border)',
              borderRadius: 'var(--radius-sm)', background: 'transparent',
              color: page === 0 ? 'var(--text-muted)' : 'var(--text-dim)',
              cursor: page === 0 ? 'default' : 'pointer',
              fontSize: '0.75rem', fontFamily: 'var(--font-sans)',
            }}
          >
            <ChevronLeft size={14} /> Newer
          </button>
          <span style={{ fontSize: '0.6875rem', color: 'var(--text-muted)' }}>
            Page {page + 1} of {totalPages}
          </span>
          <button
            onClick={() => setPage(p => p + 1)}
            disabled={page >= totalPages - 1}
            style={{
              display: 'flex', alignItems: 'center', gap: 4,
              padding: '4px 10px', border: '1px solid var(--border)',
              borderRadius: 'var(--radius-sm)', background: 'transparent',
              color: page >= totalPages - 1 ? 'var(--text-muted)' : 'var(--text-dim)',
              cursor: page >= totalPages - 1 ? 'default' : 'pointer',
              fontSize: '0.75rem', fontFamily: 'var(--font-sans)',
            }}
          >
            Older <ChevronRight size={14} />
          </button>
        </div>
      )}
    </div>
  );
}
